plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.negm.app'

    compileSdk 36

    defaultConfig {
        applicationId 'com.negm.app'

        minSdk 26
        targetSdk 35

        versionCode 1
        versionName '1.0'
    }

    buildFeatures {
        compose true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {

    implementation platform('androidx.compose:compose-bom:2026.08.00')

    implementation 'androidx.activity:activity-compose'

    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'

    implementation 'androidx.compose.foundation:foundation'

    implementation 'androidx.compose.material3:material3'

    implementation 'androidx.lifecycle:lifecycle-runtime-compose'

    debugImplementation 'androidx.compose.ui:ui-tooling'


    // Firebase

    implementation platform('com.google.firebase:firebase-bom:34.18.0')

    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-messaging'


    // WebRTC

    implementation 'io.github.webrtc-sdk:android:144.7559.14'


    // Camera / permissions

    implementation 'androidx.core:core:1.17.0'
}
